### ISSUE TITLE
Provide links for all of the dangers human kind is facing

### ISSUE THREAD

**Issue by noam-hoze** [noam-hoze/be1#10]
Please provide the latest (scientific) articles on the following topics:
- The Amazon rainforest from collapse
- Plastic pollution
- Biodegradation of natural resources
- Global nuclear threat 
- Bio-chemical weapons

Added: 
- Food insecurity
- Water pollution

**Comment by WaterHerald** [comment]
I added food insecurity and water pollution

**Comment by noam-hoze** [comment]
@WaterHerald,
Can you please add the links here?
I think it would be easier.
That way, when you add something, you don't need to update it in two places, just here.

**Comment by noam-hoze** [comment]
Hi @WaterHerald,
Reopening the issue to remind myself to add these to indiegogo.
