### ISSUE TITLE
Add a YouTube video for the song "Together"

### ISSUE THREAD

**Issue by noam-hoze** [noam-hoze/be1#5]
Add the lyrics, as presented in the deck, as the background for the video.

This link should serve people that are going to sing this together with us for practicing.

**Comment by WaterHerald** [comment]
The video was reviewed and approved Monday, April 18.

Here is the link for the final Hi-res version "Be.Together Song Tutorial:
[](https://youtu.be/oxi9Tz7SnDY)

@ 2:47 am PDT it is still processing with 2.5 hours left to render.
When this is completed I will also load it in the Be Launch Google Drive.
